# Generated by Django 4.2.28 on 2026-02-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('accounts', '0004_alter_candidate_resume_alter_candidate_skills_and_more'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'candidate')},
        ),
    ]
