# Generated by Django 4.2.28 on 2026-03-30 09:52

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[base.validators.validate_resume_extension, base.validators.validate_file_size]),
        ),
    ]
