# Generated by Django 4.2.28 on 2026-02-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=20)),
                ('experience_required', models.CharField(choices=[('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-10', '5-10 Years'), ('10-20', '10-20 Years'), ('20-30', '20-30 Years'), ('30-40', '30-40 Years'), ('40-50', '40-50 Years')], max_length=20)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recruiter')),
            ],
        ),
    ]
