# Generated by Django 4.2.28 on 2026-03-30 09:52

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[base.validators.validate_resume_extension, base.validators.validate_file_size]),
        ),
    ]
